 export default function sitemap() {
  return [
    {
      url: 'http://barbershopraszkow.pl',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
        url: 'http://barbershopraszkow.pl/polityka-prywatnosci',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.6,
      },
    {
      url: 'http://barbershopraszkow.pl/barber-bieganin',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'http://barbershopraszkow.pl/barber-biniew',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
        url: 'http://barbershopraszkow.pl/barber-daniszyn',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-dobrzyca',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-franklinow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-gorzupia',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-gorzyce-wielkie',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-grudzielec',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-gutow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-jozefow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-karminek',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-korytnica',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-krotoszyn',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-lamki',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-lewkow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-ligota',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-odolanow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-ostrow-wielkopolski',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-raszkow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-szczurawice',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-szczury',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-tomnice',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-topola-wielka',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-trzebowa',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/barber-wysocko-wielkie',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-bieganin',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-biniew',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-daniszyn',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-dobrzyca',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-franklinow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-gorzupia',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-gorzyce-wielkie',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-grudzielec',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-gutow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-jozefow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-karminek',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-korytnica',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-krotoszyn',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-lamki',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-lewkow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-ligota',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-bieganin',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-biniew',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-daniszyn',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-dobrzyca',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-franklinow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-gorzupia',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-gorzyce-wielkie',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-grudzielec',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-gutow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-jozefow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-karminek',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-korytnica',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-krotoszyn',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-lamki',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-lewkow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-ligota',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-odolanow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-ostrow-wielkopolski',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-raszkow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-szczurawice',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-szczury',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-tomnice',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-topola-wielka',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-trzebowa',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-meski-wysocko-wielkie',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-odolanow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-ostrow-wielkopolski',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-raszkow',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-szczurawice',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-szczury',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-tomnice',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-topola-wielka',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-trzebowa',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
      {
        url: 'http://barbershopraszkow.pl/fryzjer-wysocko-wielkie',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.9,
      },
  ]
}